### ISSUE TITLE
Add support for interceptors

### ISSUE THREAD

**Issue by Shehanir** [wso2/k8s-apim-operator#107]
**Description:**
Earlier there is no way to add interceptors to modify request and response flows. Need to add that support. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dinusha92** [comment]
This has been fixed with https://github.com/wso2/k8s-apim-operator/pull/108 and https://github.com/wso2/k8s-apim-operator/pull/110
