### ISSUE TITLE
Package the artifacts into a zip as the deliverable to the end user.

### ISSUE THREAD

**Issue by dinusha92** [wso2/k8s-apim-operator#41]
**Description:**

End-users (DevOps), needs to be delivered the k8s controller artefacts in a convenient manner. Hence ATM, it is best to deliver them as a zip including a well-documented readme as well.

The read me also should include the necessary instructions,
- In deploying kubernetes extension
- In deploying controller configuration (description of each configuration)
- Artifacts of the controller
- CRDs (with sample)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Shehanir** [comment]
resolved in https://github.com/wso2/k8s-apim-operator/pull/75
