### ISSUE TITLE
Migrate the existing toolkit and runtime to the latest version of micro-gw

### ISSUE THREAD

**Issue by dinusha92** [wso2/k8s-apim-operator#42]
**Description:**

The existing images in the API controller use mgw-3.0.0-beta2 images for both runtime and toolkit. This has to be changed to the latest version and modify the other changes required to compatible to controller with the latest mgw release.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Shehanir** [comment]
resolved in https://github.com/wso2/k8s-apim-operator/pull/52
