### ISSUE TITLE
Test the analytics flow with APIM operator

### ISSUE THREAD

**Issue by dinusha92** [wso2/k8s-apim-operator#43]
**Description:**

Analytics related configuration, secrets and volume mounts are being configured with the micro-gw via the APIM-Controller. Hence this flow has to be tested properly to verify the behaviour and identify the issues if there's any.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by RameshaKaru** [comment]
Tested and added necessary changes in https://github.com/wso2/k8s-apim-operator/pull/49
