### ISSUE TITLE
"UPDATE" support for kubernetes add api extension.

### ISSUE THREAD

**Issue by dinusha92** [wso2/k8s-apim-operator#45]
**Description:**

Currently, the kubernetes extension supports "kubectl add api" only. This has to be changed to support kubectl update API as well.
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by pubudu538** [comment]
This is already added. "Kubectl update api"
