### ISSUE TITLE
Obtain user namespace from the extension instead of the controller config

### ISSUE THREAD

**Issue by RameshaKaru** [wso2/k8s-apim-operator#56]
**Description:**
The user namespace is obtained by the controller config file at the moment. But the user should be able to give the preferred namespace when executing the kubectl add api & kubectl update api commands. The microgateway deployment and service should be created in this namespace from the above commands.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by pubudu538** [comment]
This is added.
