### ISSUE TITLE
Handling deletion of api and operator

### ISSUE THREAD

**Issue by RameshaKaru** [wso2/k8s-apim-operator#58]
**Description:**
At the moment when the user deletes an api or the operator; the related services, configmaps, secrets, jobs and other resources are not deleted. User will have to manually clean up all the garbage resources. The operator has to facilitate automatic deletion of related resources when user wants to delete a particular api, as well as if the user wants to delete the operator.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by pubudu538** [comment]
This is added.
