### ISSUE TITLE
Move docker config from configmap to secret

### ISSUE THREAD

**Issue by dinusha92** [wso2/k8s-apim-operator#60]
**Description:**

To push the image to the docker registry, docker config is attached to the Kaniko pod.
As of now, we are attaching it as a config map. Since this contains confidential information, we should move it to secret.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by pubudu538** [comment]
This is fixed.
