### ISSUE TITLE
Move API related resources to user namespace

### ISSUE THREAD

**Issue by RameshaKaru** [wso2/k8s-apim-operator#61]
**Description:**
As of now some API related resources are in the wso2-system namespace, while deployment and service are created in the user given namepsace. But for the user to have more insight into the workflow of the operator, all the API related resources should be in the user namespace. Also, if a user tries to add an api name which does not exist in that user namespace, but exists in another namespace; the earlier approach would give arise to an error saying kubernetes job already exists.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by pubudu538** [comment]
This is fixed.
