### ISSUE TITLE
Maintain api instance related mgw-conf and dockerfile for kaniko

### ISSUE THREAD

**Issue by RameshaKaru** [wso2/k8s-apim-operator#62]
**Description:**
As of now microgateway config file and dockerfile for kaniko job have a name which does not change according to API instances.
This is not an issue if the API instances are added sequentially, because the resources get updated according to changes.
But when an API is added before the kaniko job of the previous API instance is completed, the configuration file of the previous API can get overridden by the new changes.
Further, to connect the cascade deletion to the API, the above files need to have a connection with the api instance.
Hence it is needed to maintain separate configmaps for above files
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by pubudu538** [comment]
This is fixed.
