### ISSUE TITLE
Create sample test scenarios

### ISSUE THREAD

**Issue by RameshaKaru** [wso2/k8s-apim-operator#64]
**Description:**
To test the k8s-operator flow, it is helpful to have sample resource artifacts.
Functions to be tested:
Adding API
Update API
Delete API
Analytics
OAuth2 flow
JWT flow
Ratelimiting
Security kind
Target endpoint kind

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dinusha92** [comment]
@RameshaKaru @pubudu538 will there be any additional scenarios we need to add here? Or else we can close the issue.

**Comment by dinusha92** [comment]
Need to add sample for mgw interceptors

**Comment by dinusha92** [comment]
This has been completed. Please refer scenarios section in the root.
