### ISSUE TITLE
Add HPA when deploying the API

### ISSUE THREAD

**Issue by pubudu538** [wso2/k8s-apim-operator#84]
**Description:**
At the moment we create only the deployment and the service. We need to create the HPA for auto-scaling based on CPU limits. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Shehanir** [comment]
resolved in https://github.com/wso2/k8s-apim-operator/pull/88

**Comment by dinusha92** [comment]
Closing the issue as it is fixed with the #88 PR.
